# 00 00. PyTorch Fundamentals
https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch

print(torch.__version__)

2.6.0+cu124


#Introduction to Tensors
Creating tensors:
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

Tensors in pytroch can be initialised by using `torch.tensor()` or `torch.tensor(some_data)`

In [3]:
#scalar
scalar = torch.tensor(42)
scalar

tensor(42)

In [4]:
scalar.dim()

0

In [5]:
#to get back a python int only
scalar.item()

42

In [6]:
#Vector
vector = torch.tensor([1,2])
vector.dim()

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix

matrix = torch.tensor([[1,2,3],[4,5,6]])
print("shape:", matrix.shape)
print("dimension:", matrix.dim())
matrix[0]

shape: torch.Size([2, 3])
dimension: 2


tensor([1, 2, 3])

In [9]:
# TENSOR
TENSOR = torch.tensor([
    [ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ],

    [ [[13,14,15],[16,17,18]], [[19,20,21],[22,23,24]] ]
    ])
print(TENSOR.shape)
print(TENSOR.dim())

torch.Size([2, 2, 2, 3])
4


In [10]:
tens = torch.tensor([ [[1,1],[1,1]],[[1,1],[1,1]] ])

print(tens.shape)
print(tens.dim())

torch.Size([2, 2, 2])
3


In [11]:
x = torch.tensor([ [1],[1],[1],[1] ])
x.dim()

2

# Random Tensor

Important because NNs start out with tensors full of random numbers

In [12]:
rand = torch.rand(1,3,4)
print(rand)
rand.dim()

tensor([[[0.0493, 0.1542, 0.5872, 0.5813],
         [0.2094, 0.7129, 0.0609, 0.0273],
         [0.3255, 0.3260, 0.5979, 0.2775]]])


3

In [13]:
# Image like Tensor

img_rand_tens = torch.rand(3,255,255)
img_rand_tens

tensor([[[0.3238, 0.1820, 0.3782,  ..., 0.4328, 0.5550, 0.9875],
         [0.5849, 0.2362, 0.5719,  ..., 0.9722, 0.6912, 0.1510],
         [0.8359, 0.1641, 0.5826,  ..., 0.8750, 0.3033, 0.8417],
         ...,
         [0.0127, 0.1063, 0.9746,  ..., 0.5089, 0.7246, 0.6266],
         [0.9425, 0.3214, 0.4297,  ..., 0.6575, 0.6178, 0.4091],
         [0.8288, 0.5523, 0.4660,  ..., 0.5430, 0.4196, 0.8243]],

        [[0.3454, 0.0592, 0.6359,  ..., 0.9221, 0.0387, 0.0550],
         [0.5540, 0.4078, 0.9704,  ..., 0.2421, 0.4518, 0.7387],
         [0.8663, 0.8349, 0.7915,  ..., 0.2910, 0.4224, 0.0622],
         ...,
         [0.0254, 0.1321, 0.7150,  ..., 0.1742, 0.9779, 0.0137],
         [0.8060, 0.1137, 0.7611,  ..., 0.9235, 0.7616, 0.2278],
         [0.8103, 0.2126, 0.4114,  ..., 0.0465, 0.3440, 0.5331]],

        [[0.5520, 0.3620, 0.2506,  ..., 0.0247, 0.5642, 0.2507],
         [0.5997, 0.6285, 0.0105,  ..., 0.2916, 0.2508, 0.6920],
         [0.0147, 0.7488, 0.3294,  ..., 0.4748, 0.1010, 0.

In [14]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
ones[1] = ones[1]*zeros[1]
ones

tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.]])

In [17]:
# Range

range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# creating tensors of the same shape of ones or zeroes as other tensors

rand = torch.rand(3,5)
print(rand.shape)
ones_like_rand = torch.ones_like(rand)
print(ones_like_rand.shape)

torch.Size([3, 5])
torch.Size([3, 5])


#Data types

#tensors default to data type float32

In [19]:
float_32 = torch.tensor([1.0,2.0,3.0],
                        device=None,
                        requires_grad = False)
print(float_32.dtype)


float_16 = torch.tensor([5.0,6.0,7.0],
                        dtype = torch.float16,
                        device=None,
                        requires_grad = False)
print(float_16.dtype)


torch.float32
torch.float16


In [20]:
#can change dtype

from_32_to_16 = float_32.type(torch.float16)
print(from_32_to_16.dtype)
from_32_to_16.device

torch.float16


device(type='cpu')

#Getting Tensor Attributes


1.   To get dtype use `tensor.dtype`
2.   To get shape use `tensor.shape`
3.   To get device use `tensor.device`





In [21]:
another_tensor = torch.rand(3,4, dtype = torch.float16)

print(f"tensor data type {another_tensor.dtype}")
print(f"tensor shape {another_tensor.shape}")
print(f"tensor device location {another_tensor.device}")

tensor data type torch.float16
tensor shape torch.Size([3, 4])
tensor device location cpu


#Getting information from tensors
to get dtype use `tensor.dtype`

1.   List item
2.   List item


to get shape use `tensor.shape`
to get device use `tensor.device`

#Manipulating Tensors

In [22]:
#Addition
tensor = torch.tensor([1,2,3])
print(tensor + 10)
#tensor.add_(100) works too


tensor([11, 12, 13])


In [23]:
#Multiplication

tensor * 20

tensor([20, 40, 60])

In [24]:
#subtract
tensor - 30

tensor([-29, -28, -27])

In [25]:
torch.add(tensor, 10)


tensor([11, 12, 13])

#Matrix Multiplication

In [26]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [27]:
#matrix multiplication

print(f"{torch.matmul(tensor, tensor)}")
#or
print(f"{tensor @ tensor}")

14
14


#Tensor Shape Errors & Transposes

1. Tensors that are to be multiplied must share the same inner shape dimension e.g (3,2) @ (2,3) or (7,3) @ (3,12)

2. The outside dimensions provide the output shape e.g. for (7,3) @ (3,12) the output shape is a (7,12) Tensor.

In [28]:
TENSOR_A = torch.rand(3,2)
TENSOR_B = torch.rand(3,2)

#TENSOR_C = TENSOR_A @ TENSOR_B
#This will give a shape error because Matrix mul cannot be done


#Transpose one of the vectors to be abel to multiply them


TENSOR_C = TENSOR_A @ TENSOR_B.T
TENSOR_C
#OR
TENSOR_C = torch.matmul(TENSOR_A,TENSOR_B.T)
TENSOR_C

tensor([[0.0758, 0.1186, 0.1169],
        [0.1933, 0.1416, 0.0346],
        [0.5524, 0.3886, 0.0723]])

#Min, Max, Sum, Mean (Tensor Aggregation)

In [29]:
TENSOR = torch.arange(1,100,10)
TENSOR

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
#Min
TENSOR.min()
#or
torch.min(TENSOR)

tensor(1)

In [31]:
#Max
TENSOR.max()
#or
torch.max(TENSOR)

tensor(91)

In [32]:
#Sum
TENSOR.sum()
#or
torch.sum(TENSOR)

tensor(460)

In [33]:
#Mean
#TENSOR.mean()
#RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
#Need to change data type for .mean() to work

TENSOR.type(torch.float32).mean()
#or
torch.mean(TENSOR.type(torch.float32))

tensor(46.)

#argmin() and argmax()

In [34]:
TENSOR

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [35]:
#index position of minimum value in tensor
TENSOR.argmin()

tensor(0)

In [36]:
#index position of maximum value in tensor

TENSOR.argmax()

tensor(9)

#Reshaping, Viewing, stacking, squeezing and unsqueezing, and Permuting


In [37]:
#Adding extra dimension (reshping to (1,10) also adds extra dimension)
x = torch.arange(0.,10.)
print(x)

x = x.reshape(1,10)

print(x, x.shape)
x = x.reshape(5,2)

print("\n", x, x.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 10])

 tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([5, 2])


In [38]:
#Change the View
z = x.view(10,1)
z, z.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [39]:
# changing z changes x because they share the same memory

z[0,:] = 7
z, x

(tensor([[7.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[7., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]))

In [40]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x], dim = 2)
x_stacked


tensor([[[7., 7., 7.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [3., 3., 3.]],

        [[4., 4., 4.],
         [5., 5., 5.]],

        [[6., 6., 6.],
         [7., 7., 7.]],

        [[8., 8., 8.],
         [9., 9., 9.]]])

In [41]:
from os import remove
# torch.squeeze() removes all single dimensions from a tensor
tensor = torch.rand((1,3,1,3))
print(f"previous tensor: {tensor}")
print(f"\nprevious tensor shape: {tensor.shape}")

#remove extra single dimensions from tensor
squeezed_t = tensor.squeeze()
print(f"\nSqueezed tensor: {squeezed_t}")
print(f"\n Squeeze tnesor shape: {squeezed_t.shape}")

previous tensor: tensor([[[[0.4563, 0.6102, 0.2477]],

         [[0.2880, 0.1393, 0.8948]],

         [[0.4249, 0.6359, 0.9089]]]])

previous tensor shape: torch.Size([1, 3, 1, 3])

Squeezed tensor: tensor([[0.4563, 0.6102, 0.2477],
        [0.2880, 0.1393, 0.8948],
        [0.4249, 0.6359, 0.9089]])

 Squeeze tnesor shape: torch.Size([3, 3])


In [42]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"previous tensor: {squeezed_t}")
print(f"\nprevious tensor shape: {squeezed_t.shape}")

unsqueezed_t = squeezed_t.unsqueeze(dim=2)

print(f"\nUnsqueezed tensor: {unsqueezed_t}")
print(f"\nUnsqueezed tensor shape: {unsqueezed_t.shape}")


previous tensor: tensor([[0.4563, 0.6102, 0.2477],
        [0.2880, 0.1393, 0.8948],
        [0.4249, 0.6359, 0.9089]])

previous tensor shape: torch.Size([3, 3])

Unsqueezed tensor: tensor([[[0.4563],
         [0.6102],
         [0.2477]],

        [[0.2880],
         [0.1393],
         [0.8948]],

        [[0.4249],
         [0.6359],
         [0.9089]]])

Unsqueezed tensor shape: torch.Size([3, 3, 1])


In [43]:
# torch.permute - arranges the dimensions of a target tensor in a specified order
x_original = torch.rand(640, 480,3) #[height, width, colour_channels]
print(f"Original shape: {x_original.shape}")
# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = torch.permute(x_original, (2,0,1))
print(f"\nPermuted tensor shape: {x_permuted.shape}") #now [colour_channels, height, width]
# x_permuted is a different view of x_original so they share the same memory (check documentation)

Original shape: torch.Size([640, 480, 3])

Permuted tensor shape: torch.Size([3, 640, 480])


In [44]:
#to show that x_permuted is a VIEW of x_original

x_original[0,0,0] = 424242

print(f"first element of x_original: {x_original[0,0,0]}")
print(f"\nfirst element of x_permuted: {x_permuted[0,0,0]}")

first element of x_original: 424242.0

first element of x_permuted: 424242.0


# Indexing tensors
similar to numpy



In [45]:
x = torch.arange(1,10)
x = x.reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [46]:
# Indexing on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [47]:
# Indexing on middle bracket (dim = 1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [48]:
# Indexing on inner most bracket (last dimension)
x[0][2][-1], x[0,2,-1]

(tensor(9), tensor(9))

In [49]:
# Can also use ":" to select all of the target dimension
#notice difference in indexing convention and result
# x[:] just makes a shallow copy of the same tensor
x[:,0], x[:][0]

(tensor([[1, 2, 3]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

✅ Why `x[:, 0`] is better:
Clearer: It immediately shows you're slicing along specific dimensions.

More efficient: PyTorch doesn't make an unnecessary shallow copy like it does with `x[:]`.

Consistent with multi-dimensional slicing: You can easily expand this to 3D, 4D, etc., without confusion.

In [50]:
#more exmaples
x[:,:,1]

tensor([[2, 5, 8]])

In [51]:
x[:,1,1]

tensor([5])

In [52]:
x[0,0,:]

tensor([1, 2, 3])

In [53]:
# indexing on x to return 9
x[0,2,2], x[0,-1,-1]

(tensor(9), tensor(9))

In [54]:
# index to return 3,6,9

x[0,:,2]

tensor([3, 6, 9])

# Pytorch tensors and Numpy

Pytorch has functionality to intereact with NumberType

* Data in Numpy, want it in PyTorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [55]:
import numpy as np

array = np.arange(1.,10.)
tensor = torch.from_numpy(array) #WARNING the ternsor will inherit the np.array data type

array.dtype, tensor.dtype

#can easily convert to float32


(dtype('float64'), torch.float64)

In [56]:
#PyTorch defaults to float32
pytrotch_dtype = torch.rand(1,3)
pytrotch_dtype.dtype

torch.float32

In [57]:
#Does changing array change the tensor?
array = array + 1

array, tensor

#nope

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [58]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [59]:
# Does changing the tensor chage the array?

tensor = tensor + 1

tensor, numpy_tensor

#nope

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducubulity (removing the randomness)

In [60]:
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)

#comparing the two showing all numbers are random
print(rand_tensor_A == rand_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) #Set it before every instance of rand
rand_tensor_D = torch.rand(3,4)

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Using GPUs

In [62]:
# use command to check GPU info
!nvidia-smi

Sun Apr 13 19:20:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## 2. Check for GPU access with PyTorch

In [63]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

# Setup device agnostic code

Since PyTorch is capable of running on GPU or CPU, it's best practice to setup device agnostic code.

E.g run on GPU if available, else dafault to CPU.

https://pytorch.org/docs/stable/notes/cuda.html

In [64]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
GPU results in faster computations

In [66]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [67]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to CPU

In [76]:
# If tensor is on GPU, can't transform it to Numpy
#tensor_on_gpu.numpy() will give
#"TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first."

In [74]:
#changes it to cpu and then to numpy
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

In [75]:
#we reasigned the variable only so a copy exists
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')